<section class="hero"><div class="container hero-inner"><div class="hero-copy"><h1>CẦN KEO GÌ?<br><strong>SAHA</strong> CÓ ĐỦ</h1><p>Keo silicone • Keo xây dựng • Keo công nghiệp<br>Chính hãng • Giá tốt • Giao nhanh toàn quốc</p><div class="hero-buttons"><a class="btn btn-primary" href="#products">Xem sản phẩm →</a><button class="btn btn-light" onclick="showToast('Đã gửi yêu cầu báo giá sỉ')">Nhận báo giá sỉ ▧</button></div></div><div class="hero-products"><div class="pedestal"></div><div class="bottle">APOLLO</div><div class="bottle">APOLLO</div><div class="bottle">LOCTITE</div><div class="bottle">WACKER</div><div class="bottle">X’TRASEAL</div><div class="bottle">SAMBO</div></div></div></section>
  <div class="container floating-features"><div class="features"><div class="feature"><div class="feature-icon">♢</div><div><b>Hàng chính hãng</b><small>100% chính hãng<br>CO/CQ đầy đủ</small></div></div><div class="feature"><div class="feature-icon">□</div><div><b>Sẵn kho số lượng lớn</b><small>Đa dạng chủng loại<br>Đáp ứng nhanh</small></div></div><div class="feature"><div class="feature-icon">☷</div><div><b>Giao hàng toàn quốc</b><small>Nội thành 24h – 48h</small></div></div><div class="feature"><div class="feature-icon">▧</div><div><b>Xuất hóa đơn VAT</b><small>Hỗ trợ doanh nghiệp</small></div></div><div class="feature"><div class="feature-icon">⚙</div><div><b>Tư vấn kỹ thuật</b><small>Đội ngũ chuyên sâu</small></div></div></div></div>
  <main>
    <section><div class="container"><div class="category-grid" id="categories"></div></div></section>
    <section id="products"><div class="container"><div class="section-head"><h2>Sản phẩm bán chạy</h2><a href="#">Xem tất cả sản phẩm →</a></div><div class="product-grid" id="productGrid"></div></div></section>
    <section id="applications"><div class="container"><div class="section-head"><h2>Chọn theo ứng dụng</h2><a href="#">Xem tất cả ứng dụng →</a></div><div class="applications" id="applicationGrid"></div></div></section>
    <section id="brands"><div class="container"><div class="section-head"><h2>Thương hiệu nổi bật</h2><a href="#">Xem tất cả thương hiệu →</a></div><div class="brands"><div class="brand">APOLLO</div><div class="brand">WACKER</div><div class="brand">BAMBOO</div><div class="brand">LOCTITE</div><div class="brand">ATM</div><div class="brand">KINGBOND</div></div></div></section>
    <section id="promos"><div class="container"><div class="section-head"><h2>Khuyến mãi / Combo nổi bật</h2></div><div class="promo-grid" id="promoGrid"></div></div></section>
    <section><div class="container"><div class="about-stats"><div class="about"><img src="https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=700&q=80" alt="Kho hàng SAHA"><div class="about-copy"><h3>TỔNG KHO KEO DÁN SAHA</h3><p>Đối tác tin cậy của mọi công trình</p><ul><li>Sản phẩm chính hãng 100%</li><li>Giá tốt – Chiết khấu hấp dẫn</li><li>Giao hàng nhanh toàn quốc</li><li>Tư vấn kỹ thuật tận tâm</li></ul></div></div><div class="stats"><div class="stat"><b>10+</b><span>Năm kinh nghiệm</span></div><div class="stat"><b>50+</b><span>Thương hiệu uy tín</span></div><div class="stat"><b>20.000+</b><span>Sản phẩm đa dạng</span></div><div class="stat"><b>5.000+</b><span>Khách hàng tin tưởng</span></div></div></div></div></section>
    <section id="news"><div class="container"><div class="section-head"><h2>Tin tức / Hướng dẫn chọn keo</h2><a href="#">Xem tất cả bài viết →</a></div><div class="news-grid" id="newsGrid"></div></div></section>
  </main>